trigger:
  - dev

pool:
  vmImage: ubuntu-latest

variables:
  - group: "node-app-amplify"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "12.16.1"
            displayName: "Install Node.js"

          - script: |
              yarn install
       #       yarn run build
            displayName: "yarn install and build"

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/*"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true
            displayName: Compress the ./dist folder

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              ArtifactName: $(Build.BuildId)
            displayName: Publish build artifacts